import { Annotation, StaveNote } from "vexflow";

export const rudiments = [
    {
        id: "single_stroke",
        name: "Single Stroke",
        handOrder: "R L R L R L R L R L R L R L R L",
        bpmRecord: 0,
        staveNotes: [
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
        ],
    },
    {
        id: "double_stroke",
        name: "Double Stroke",
        handOrder: "R R L L R R L L R R L L R R L L",
        bpmRecord: 0,
        staveNotes: [
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("R")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
            new StaveNote({ keys: ["C/5"], duration: "16" }).addModifier(new Annotation("L")),
        ],
    },
]